name: video_player_example
description: Demonstrates how to use the video_player plugin.
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.6
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/cannot_read_duration_in_android.mp4
    - assets/can_read_duration_in_android.mp4
    - assets/cannot_read_duration_in_android_fixed.mp4
    - assets/ios_cannot_display_video.mp4
    - assets/ios_fixed_video.mp4

